application: jupiteractivesensor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bundles/bootstrap
  static_dir: bundles/bootstrap-3.3.2-dist
 

- url: /bundles/jquery
  static_dir: bundles/jquery
  
- url: /bundles/chart
  static_dir: bundles/chart

- url: /bundles/jasConsole
  static_dir: bundles/jasConsole

- url: /Admin/.*
  login: admin
  secure: always
  script: backoffice.app

- url: /Console/.*
  login: required 
  secure: always
  script: console.app

- url: /API/.*
  script: restapi.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"
